- 
  name: Database Installation
  hosts: Ansible-Client
  tasks:
  - name: Install MariaDB package
    yum:
      name:
      - mariadb-server
      - MySQL-python
      state: installed

  - name: Start MariaDB Service
    service: name=mariadb state=started enabled=yes

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: insert firewalld rule
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

