- name: Deploy ecommerce application
  yum:
    name:
      - libselinux-python
      - libsemanage-python
      - firewalld
    state: installed

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='localhost' state=present

- name: Move db-load-script to db host
  copy:
    src: files/db-load-script.sql
    dest: /tmp/db-load-script.sql

- name: Load Inventory Data
  shell: mysql -f < /tmp/db-load-script.sql
          

- name: Install php
  yum:
    name:
      #- httpd
      - php
      - php-mysql
    state: present

- name: Install web role specific dependencies
  yum: name=git state=installed

#- name: Start firewalld
#  service: name=firewalld state=started enabled=yes

#- name: insert firewalld rule for httpd
 # firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: Set index.php as the default page
  tags: "Set index.php as the default page"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: 'DirectoryIndex index.php'

#- name: http service state
 # service: name=httpd state=started enabled=yes
  
- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/  force=yes

- name: Update remote server ip in index.php
  command: sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php
